package com.hana.sns.mock

import com.hana.sns.post.domain.Post
import com.hana.sns.post.service.port.PostRepository
import java.util.concurrent.atomic.AtomicLong

class FakePostRepository : PostRepository {
    private val autoGeneratedId: AtomicLong = AtomicLong(0)
    var data = mutableListOf<Post>()
    override fun save(post: Post): Post {
        if(post.id == 0 || post.id == null) {
            post.id = autoGeneratedId.incrementAndGet().toInt()
            data.add(post)
        } else {
            data.removeIf { it.id == post.id }
            post.id = autoGeneratedId.incrementAndGet().toInt()
            data.add(post)
        }
        return post
    }

    override fun findById(id: Int): Post? {
        return data.find { it.id == id }
    }


}