package com.hana.sns.mock

import com.hana.sns.user.domain.User
import com.hana.sns.user.service.port.UserRepository
import java.util.concurrent.atomic.AtomicLong

class FakeUserRepository : UserRepository {

    private val autoGeneratedId: AtomicLong = AtomicLong(0)
    var data = mutableListOf<User>()

    override fun findByUserName(userName: String): User? {
        return data.find { it.userName == userName }
    }

    override fun save(user: User): User {
        if(user.id == 0 || user.id == null) {
            user.id = autoGeneratedId.incrementAndGet().toInt()
            data.add(user)
        } else {
            data.removeIf { it.id == user.id }
            user.id = autoGeneratedId.incrementAndGet().toInt()
            data.add(user)
        }
        return user
    }
}