package com.hana.sns.mock

import com.hana.sns.post.domain.Comment
import com.hana.sns.post.service.port.CommentRepository
import java.util.concurrent.atomic.AtomicLong

class FakeCommentRepository : CommentRepository {
    private val autoGeneratedId: AtomicLong = AtomicLong(0)
    var data = mutableListOf<Comment>()
    override fun save(comment: Comment): Comment {
        if(comment.id == 0L || comment.id == null) {
            comment.id = autoGeneratedId.incrementAndGet()
            data.add(comment)
        } else {
            data.removeIf { it.id == comment.id }
            comment.id = autoGeneratedId.incrementAndGet()
            data.add(comment)
        }
        return comment
    }

    fun findById(id: Long): Comment? {
        return data.find { it.id == id }
    }

}
