package com.hana.sns.mock

import com.hana.sns.post.domain.Post
import com.hana.sns.post.domain.PostLike
import com.hana.sns.post.service.port.PostLikeRepository
import com.hana.sns.user.domain.User
import java.util.concurrent.atomic.AtomicLong

class FakePostLikeRepository : PostLikeRepository {
    private val autoGeneratedId: AtomicLong = AtomicLong(0)
    var data = mutableListOf<PostLike>()


    override fun findByUserAndPost(user: User, post: Post): PostLike? {
        return data.find { it.user == user && it.post == post }
    }

    override fun save(postLike: PostLike): PostLike {
        if(postLike.id == 0 || postLike.id == null) {
            postLike.id = autoGeneratedId.incrementAndGet().toInt()
            data.add(postLike)
        } else {
            data.removeIf { it.id == postLike.id }
            postLike.id = autoGeneratedId.incrementAndGet().toInt()
            data.add(postLike)
        }
        return postLike
    }

    fun findById(id : Int): PostLike? {
        return data.find { it.id == id }
    }
}
